CREATE TABLE IF NOT EXISTS postjob (
    id UUID PRIMARY KEY NOT NULL,
    jobd VARCHAR(255) DEFAULT NULL,
    jtittle VARCHAR(255) DEFAULT NULL,
    jskills VARCHAR(255) DEFAULT NULL,
    jtype VARCHAR(255) DEFAULT NULL,
    jsalary VARCHAR(255) DEFAULT NULL,
    jcname VARCHAR(255) DEFAULT NULL,
    jcemail VARCHAR(255) DEFAULT NULL
    );
